version = 0.1
[default.deploy.parameters]
stack_name = "demo-card-bot-3"
resolve_s3 = true
s3_prefix = "demo-card-bot-3"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
